import { ListingOnMap } from "../types/global.types";

export const listingsOnMap: ListingOnMap[] = [
  {
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [-79.727397, 43.763645],
    },
    properties: {
      id: "65ebf60289d2db0b985f35ae",
      filters: {
        security_cameras: false,
        full_day_access: false,
        ev_charging: false,
        handicap_accessible: false,
        storage_type: "outdoor",
        vehicle_type: "sedan / suv",
        length: 20,
        width: 10,
        spaces: 2,
      },
      address: {
        street: "2 narrow valley crescent",
        lng: "-79.727397",
        lat: "43.763645",
        state: "null",
        city: "brampton",
        zip: "L6R 2M6",
        country: "CA",
      },
      description: "n/a",
      price: { daily: 16, monthly: 500 },
      is_available: true,
      images: [""],
      listed_on: "2023-nov-30",
      is_scraped: true,
      contact: "+1-6474666681",
    },
  },
  {
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [-79.731989, 43.760685],
    },
    properties: {
      id: "65ebf60789d2db0b985f35b1",
      filters: {
        security_cameras: false,
        full_day_access: false,
        ev_charging: false,
        handicap_accessible: false,
        storage_type: "outdoor",
        vehicle_type: "sedan / suv",
        length: 20,
        width: 10,
        spaces: 1,
      },
      address: {
        street: "109 mountainash road",
        lng: "-79.731989",
        lat: "43.760685",
        state: "null",
        city: "brampton",
        zip: "L6R 1H7",
        country: "CA",
      },
      description: "n/a",
      price: { daily: 2, monthly: 70 },
      is_available: true,
      images: [""],
      listed_on: "2023-nov-22",
      is_scraped: true,
      contact: "+1-6474675091",
    },
  },
  {
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [-79.637292, 43.725185],
    },
    properties: {
      id: "65f7a5cac7813795ff25f4f8",
      filters: {
        security_cameras: false,
        full_day_access: false,
        ev_charging: false,
        handicap_accessible: false,
        storage_type: "outdoor",
        vehicle_type: "sedan / suv",
        length: 20,
        width: 10,
        spaces: 1,
      },
      address: {
        street: "7450 darcel avenue",
        lng: "-79.637292",
        lat: "43.725185",
        state: "null",
        city: "mississauga",
        zip: "L4T 2X5",
        country: "CA",
      },
      description: "n/a",
      price: { daily: 3, monthly: 100 },
      is_available: true,
      images: [""],
      listed_on: "2024-feb-28",
      is_scraped: true,
      contact: "+1-6477066314",
    },
  },
  {
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: [-79.665686, 43.694445],
    },
    properties: {
      id: "65f7a5c6c7813795ff25f4f5",
      filters: {
        security_cameras: false,
        full_day_access: true,
        ev_charging: false,
        handicap_accessible: false,
        storage_type: "outdoor",
        vehicle_type: "commercial truck / trailer",
        length: 40,
        width: 10,
        spaces: 5,
      },
      address: {
        street: "2201 drew road",
        lng: "-79.665686",
        lat: "43.694445",
        state: "null",
        city: "mississauga",
        zip: "L5S 1E5",
        country: "CA",
      },
      description: "n/a",
      price: { daily: 13, monthly: 400 },
      is_available: true,
      images: [""],
      listed_on: "2024-mar-11",
      is_scraped: true,
      contact: "+1-4376623042",
    },
  },
];
