name: Deploy React App to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn

    - name: Build the project
      env:
        MODE: production
        VITE_REACT_APP_CLIENT_URL: https://rentaparking.ca/api
        VITE_MAPBOX_ACCESS_TOKEN: pk.eyJ1IjoiY29kZXJzYmV5b25kIiwiYSI6ImNsc3ZhYmk1NjBobnQya3JxaWoyYXpleXoifQ.igcdok9oqUQAML9i3gyH_w
        VITE_AMPLITUDE_KEY: f664e4e6176d2e3252569402be95bc56
      run: yarn build

    - name: move files to dist
      run: cp sitemap.xml dist/

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PARKBNB_GH_ACTION_SSHKEY_V2 }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 209.38.8.8 >> ~/.ssh/known_hosts

    - name: Copy build files to server
      run: |
        scp -r dist/* root@209.38.8.8:/var/www/netflix/client/

    - name: Restart Nginx on server
      run: |
        ssh root@209.38.8.8 "systemctl restart nginx"
